Secure data in aws
reflectoring/reflectoring.github.io pull request #376
Opened 2021-04-24 15:08 UTC by arkuksin

Please re-read your article a day or so after you finished writing it and work through this checklist to polish the quality. This will save all of us a lot of time during review.

## Content
- [ ] the article explains *why* and not only *how*
- [ ] (half-)sentences that express a meaningful idea that is understandable by itself own are **bold** to allow quick scanning of the text

## Text
- [ ] the text is conversational ("we" instead of "you", easy language)
- [ ] there are no "walls of text" (short sentences, short paragraphs with a single idea)
- [ ] the text is inclusive ("the developers" and "they" instead of "the developer" and "he/she")
- [ ] the text uses active voice instead of passive voice
- [ ] names are spelled consistently throughout the article (correct uppercase / lowercase)
- [ ] file names and variables are highlighted as `code`

## Structure
- [ ] the article has a short intro before the first headline
- [ ] by reading the table of contents (TOC) alone, I get a sense of the "story" of the article (check the TOC in the preview after raising the PR or by starting the blog locally on your machine)
- [ ] if using sub-headlines, there's at least two sub-headlines below a main-headline
- [ ] headlines are consistent throughout the article (same level of abstraction, same style - if one headline starts with a verb in imperative form, the other headlines on the same level should probably, too)

## Code Examples
- [ ] code examples are introduced with a ":" and explained below the code example
- [ ] code examples are formatted to avoid horizontal scrolling (manual line breaks and 2-spaces indentation)
- [ ] the text has been checked with [Grammarly](https://grammarly.com) (the free tier is enough)

**Feel free to raise the PR even if the checklist hasn't been worked through, yet**, to take advantage of the preview that is generated for each pull request (see "deploy/netlify" under "Show all checks"). But please only flag it to be reviewed after going through the checklist above.

2021-05-03 22:20 UTC, pratikdas requested changes

2021-05-04 19:54 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
I restructured it. It has two parts: Advantages of KMS and Working with KMS

2021-05-04 19:55 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
I put it a separate section.

2021-05-04 19:55 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
I put in the section "Working with KMS"

2021-05-04 19:55 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
Done

2021-05-04 19:59 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +It is the case if the application requires a key management. The application can use the existing solution of KMS
moved to the section of advantages.

2021-05-04 20:00 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
I put it a a separate section and added link to pricing pages.

2021-05-04 20:00 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
I removed some parts.

2021-05-04 20:01 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
Done

2021-05-04 20:01 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
I removed some parts

2021-05-04 20:01 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
Done

2021-05-04 20:01 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
Done

2021-05-04 20:02 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
Done

2021-05-04 20:02 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +We said several times, that a key is stored in KMS. But what does it mean to store the key in KMS? KMS uses a Cloud HSM service
I rephrased it and tried to explain it.

2021-05-04 20:03 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +in AWS data center. Keys, that are created in this HSM are not shared with other AWS customers. They are located
I remove the word "device" and replaced it by dedicated hardware, because we get dedicated HSMs from AWS.

2021-05-04 20:04 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +Since we get a device from AWS, it is important to understand what an AWS customer can do on the HSM and what does
I rephrased and removed some parts

2021-05-04 20:04 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
Restructered.

2021-05-04 20:06 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +
I am not sure, I understand your point. I wrote about the advantages and disadvantages of both services KMS and CloudHSM, and now I explain how to integrate them to have the benefits of both services at once.

2021-05-04 20:11 UTC, arkuksin commented on _posts/2021-04-20-securing-data-on-aws.md
> +---
grammerly doesn't show any issues more.

2021-05-06 21:01 UTC, merged