A Reactive Architecture using Spring Boot
reflectoring/reflectoring.github.io pull request #467
Opened 2022-04-18 15:18 UTC by arpendu11

Please read through the [writing guide](https://reflectoring.io/contribute/writing-guide/) before submitting a pull request and go through this checklist (at least for your first article).

**Feel free to raise the pull request even if the checklist hasn't been worked through, yet**, to take advantage of the online preview that is generated for each pull request (see "deploy/netlify" under "Show all checks" in your pull request). But please only flag it to be reviewed by your editor after going through the checklist.

## Review
- [ ] you have reviewed the text a day after finishing it (you'd be surprised how many errors you can avoid by just getting some distance to what you've written)

## Content
- [ ] the article explains *why* and not only *how*
- [ ] (half-)sentences that express a meaningful idea that is understandable by itself own are **bold** to allow quick scanning of the text
- [ ] the text has been checked with [Grammarly](https://grammarly.com) (the free tier is enough)

## Text
- [ ] the text is conversational ("we" instead of "you", easy language)
- [ ] there are no "walls of text" (short sentences, short paragraphs with a single idea)
- [ ] the text is inclusive ("the developers" and "they" instead of "the developer" and "he/she")
- [ ] the text uses active voice instead of passive voice
- [ ] names are spelled consistently throughout the article (correct uppercase / lowercase)
- [ ] file names and variables are highlighted as `code`

## Structure
- [ ] the article has a short intro before the first headline
- [ ] by reading the table of contents (TOC) alone, I get a sense of the "story" of the article (check the TOC in the preview after raising the PR or by starting the blog locally on your machine)
- [ ] if using sub-headlines, there's at least two sub-headlines below a main-headline
- [ ] headlines are consistent throughout the article (same level of abstraction, same style - if one headline starts with a verb in imperative form, the other headlines on the same level should probably, too)

## Code Examples
- [ ] code examples are introduced with a ":" and explained below the code example
- [ ] code examples are formatted to avoid horizontal scrolling (manual line breaks and 2-spaces indentation)

2022-05-04 20:25 UTC, thombergs requested changes
Great article again! I left some comments, please have a look. Please do a `git pull` before you change anything, because I pushed some minor changes.

2022-05-05 08:46 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +image: images/stock/0122-blocks-4480x6720.jpg
Thats fine! I couldn't find more suitable image. So if you get any please replace.

2022-05-05 08:46 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +When we start building an application from scratch or try to build an application for a startup, we tend to build a single monolith application mapped to a single database. Over time, as the system a
I have replaced this whole paragraph with less words and more technical description.

2022-05-05 08:46 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +In microservices, each service practically takes care of its data and persistence. Then there is always an orchestration between these services and they interact with each other synchronously or asyn
I have added few lines in previous paragraph which may clarify why we need atomicity along with synchronicity between the microservices.

2022-05-05 08:46 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +# Brief Introduction to Reactive Systems
Thanks! I will take care of it next time.

2022-05-05 08:46 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +Let’s define a Transaction model to receive the incoming information.
Thanks! I will take care of it next time.

2022-05-05 08:47 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +                        secondProcessed = restTemplate.postForObject(ACCOUNT_MANAGER_SERVICE_URL, firstProcessed, Transaction.class);
I have added line breaks wherever necessary so that it wont look ugly.

2022-05-05 08:47 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +Keeping this in mind, let’s try to convert our existing microservice to adapt Reactive frameworks. We will primarily use *Reactive Spring Data Mongo* which provides out-of-the-box support for reactiv
Thanks! I will take care of it next time.

2022-05-05 08:47 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +{{% image alt="Reactive Spring Microservice" src="images/posts/spring-reactive-architecture/reactive-spring-microservice.png" %}}
The previous image has API communication using Spring Web. In this image we are communicating using WebClient and Spring WebFlux. That's the major difference I wanted to portray. So I feel its still relevant here.

2022-05-05 08:47 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +```
I have added few description to describe more about the sequence between each component for the sake of orchestration.

2022-05-05 20:27 UTC, thombergs commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +When we start building an application from scratch or try to build an application for a startup, we tend to build a single monolith application mapped to a single database. Over time, as the system a
I simplified it even a bit more. Please have a look as inspiration for the next article :)

2022-05-05 21:00 UTC, thombergs requested changes

2022-05-07 07:18 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-using-spring-boot.md
> +{{% image alt="Reactive Spring Microservice" src="images/posts/spring-reactive-architecture/reactive-spring-microservice.png" %}}
I have added a description to point the diff between both the images.

2022-05-07 07:19 UTC, arpendu11 commented on content/blog/2022/2022-04-18-reactive-architecture-with-spring-boot.md
> +Thus, it usually makes sense to bring atomicity within the services to bring in continuous and streamlined data flow and make the interactions and network calls asynchronous to address the problem of
I have rephrased those 3 paragraphs. Please review if this looks meaningful.

2022-05-07 20:46 UTC, merged